apiVersion: batch/v1
kind: CronJob
metadata:
  name: my-ip-address
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: my-ip-address
            image: gcr.io/google-samples/node-hello:1.0
            command:
            - /bin/bash
            - -c
            - date; curl 2ip.ru
